### ISSUE TITLE
hamburger.js file in the javascripts file is not being used anywhere

### ISSUE THREAD

**Issue by AmalHussein** [awesomefoundation/awesomebits#121]
jQuery code in the hamburger.js file is not being used in the nav bar. 

jQuery(function($) {
  $('.hamburger').click(function() {
    $(this).parent().toggleClass('shownav');
  });
});

Possible, remove?

**Comment by jcn** [comment]
This is definitely being used by the mobile version of the admin site (though the public site isn't responsive yet). Closing this issue.
