### ISSUE TITLE
Migrate to Rails 4.2

### ISSUE THREAD

**Issue by tibbon** [awesomefoundation/awesomebits#125]
This would be a relatively large undertaking, but should happen at some point.

**Comment by jcn** [comment]
Keeping this issue active. I'm making an active effort to have this done by the 2019 summit, so the plan will be to migrate through all of the major and minor versions incrementally. As things are progressing I'll push to a feature branch for review as appropriate. 

Just posting here in case some lunatic is also thinking about doing this.

**Comment by tibbon** [comment]
I just might be that lunatic. I've been working on Rails updates at work, and I've gotten pretty good at it actually. If you wanna set up some weekend where we could remotely pair and rip through a good bit, I bet we could get a lot done then. My only real worry is that there's some old gems we rely on that don't upgrade well.

**Comment by jcn** [comment]
@tibbon I'll be honest, I don't think I'm going to be very good at pairing on this particular project as I was planning on just tearing through it one minor release at a time. If I run into a blocker though I might reconsider.

You're right about the gems, but we'll figure that out as we go. My approach has been to be pretty conservative and just get the minimum set of updated done per update, just to get things running, so we're not trying to update the universe all at once.

That said, if it'd be easy enough to update/redo #118 that'd be great, though I was also just going to get that done before the upgrade so I might beat you to it. :)

**Comment by tibbon** [comment]
Oh yea I can redo #118 easily now since Rubocop can do most of it for me.

**Comment by tibbon** [comment]
Also, whoa looking at this project I realize just how much better I am with Ruby/Rails than I was ~6 years ago! I really barely knew what I was doing then.

**Comment by jcn** [comment]
We're going to do this even more incrementally. We're going to get 4.2 running and deployed, and then we'll work on Rails 5.
