### ISSUE TITLE
Customizable new application email response

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#156]
The email that gets sent to users after submitting a submission should be customizable so chapters can include their own contact info, etc. 

Requirements:
- Editable chunk of text to be inserted into the email, editable on the chapter editing page
- Insert the text on this page: https://github.com/awesomefoundation/awesomebits/blob/master/app/views/project_mailer/new_application.text.erb
- Chapters need to have default text both for existing chapters and new chapters

**Comment by arsduo** [comment]
Just submitted code for this! 

Since the email form currently doesn't support localization I chose not to add any -- we can do that separately if we want to.

**Comment by jcn** [comment]
This has been merged in. I agree that getting this feature out the door was more important than futzing with localization, especially since the old response wasn't localized. We can work on that in the future.

Thanks @arsduo! :100:
