### ISSUE TITLE
Add ability for trustees to comment on submissions

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#157]
This needs a little more discussion, but it was an idea that was floated at the 2014 Awesummit. Mostly, we were looking for a way for trustees to comment on projects, internally, for discussion. 

There are a number of questions that need to be answered though:
- ~~Notifications - who do email notifications go to, if anyone? The dean of the chapter that the project belongs to? Other people who have commented? Nobody? Maybe you can tag another person to notify them when you're commenting.~~ - Not in the first iteration
- Who gets to comment? Can you comment on any chapter's projects? 
- ~~Do comments end up in the search results?~~ - Not in first iteration
- Can comments be deleted? By whom?

**Comment by emdaniels** [comment]
Initial requirements:

- edit and delete privileges for admin and trustee
- deans can delete things from within own chapter
- not limited to area- trustees can comment on anything
- single threaded, attached to application
- person, date/time (store in UTC, display in timezone of chapter) displayed on each comment
- collapsable by default some kind of notice that there are comments in main page
- expanded by default in individual view
- not searchable yet
- strip html/sanitize before sending to db
