### ISSUE TITLE
New About Us content

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#160]
This content will need to be localized as well. Please see #109 for an internationalization technique I think we should use.

~~https://docs.google.com/document/d/1q4NMJr9wOuJsd33oB3tSIG4rgzg6tucTLTEgug3YNSI/edit~~
https://docs.google.com/document/d/1UjOjXPYrta8E60RpPzN7Dud27B1AwT_E3bE8_kh8-5s/edit

**Comment by avicaplan** [comment]
Thanks for updating the link with my edits. Think this is good to go!

**Comment by jcn** [comment]
We're missing the new Russian translation but the framework is in place so I'm closing this.
