### ISSUE TITLE
Alphabetize chapter lists and menus to no longer give precedence to U.S. and Canada

### ISSUE THREAD

**Issue by avicaplan** [awesomefoundation/awesomebits#165]
As discussed on the global list, the time has probably come to present ourselves as fully international.

**Comment by avicaplan** [comment]
I think the discussion has effectively concluded, and we should proceed with this.

**Comment by avicaplan** [comment]
At the same time, we should move the "Worldwide" section to the end of the list, as there is effectively only one worldwide chapter left (Awesome Without Borders), and the New Chapters Team is skeptical about creating new ones given the track record.

**Comment by avicaplan** [comment]
Just another ping on this one, as growth in US chapters means we now have nearly no third column in the list.

**Comment by jcn** [comment]
OK, this has been changed, and now it looks a little funny because we're not breaking chapters in the middle, but we can address that in a later ticket. For now though, the US and Canada are no longer prioritized anywhere - in the chapter list in the nav, or in the application form.

**Comment by avicaplan** [comment]
Alternate solution: sign up another 30 or so non-US chapters. ;)

**Comment by jcn** [comment]
Now you’re thinking!
