### ISSUE TITLE
Error updating photos on specific project

### ISSUE THREAD

**Issue by frabcus** [awesomefoundation/awesomebits#167]
On this project, if I reorder the photos (or try deleting them) when I do "Save" it shows just a blank page, and makes no changes.

http://www.awesomefoundation.org/en/projects/42798-flag-for-liverpool/edit

**Comment by jcn** [comment]
I'm not seeing this problem. I tried saving without reordering, and it seems to work (redirects to the public page) and I reorder the images and save and that works too. Can you try again? It may have been a momentary hiccup with the actual installation, vs a problem with the code.=

**Comment by jcn** [comment]
Closing this issue as there have been no additional reports of this error.

**Comment by frabcus** [comment]
Yep - works fine for me now. I've no idea what was going on.
