### ISSUE TITLE
Better image display on funded project pages

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#174]
The main problem here is that we ask for people to upload photos with a 2:1 aspect ratio, and the website is _only_ designed to display photos with that ratio. See for example the following:

![screen shot 2018-06-22 at 4 47 31 pm](https://user-images.githubusercontent.com/2909/41798598-3dea4f32-763c-11e8-855a-aff8627188df.png)

Above is what is displayed on this project page. 

The actual photo being uploaded however is:

![trike_at_night](https://user-images.githubusercontent.com/2909/41798610-499315bc-763c-11e8-98d0-61fbd8cd61aa.jpg)

Since it seems clear that users are just going to upload images with non-conforming aspect ratios  there are a couple of ways of handling this:

- Handle the image gallery by loading full-sized images in a lightbox (_Using a lightbox interface should fix Issue #100 as well_)
- Provide a cropping interface for the "main" image that displays on the project page

or

- Provide a cropping interface for all of the images for a funded project only, since we display the original images in the application review process, and keep the layout of the project page the same as it currently is

or

- Redesign the project page to handle arbitrary image sizes, but I think that seems like a fight not worth fighting, and will probably require some sort of cropping interface anyway. 

Note: This project specifically does not involve the dashboard display of images which is Issue #173.

**Comment by jpotter** [comment]
Is it easy to redesign the project page to scale/crop the image with some amount of responsive design in play? I.e. don't change the design much, but enough that the image resizes to the bounds of some div layer?

**Comment by jcn** [comment]
The issue isn't resizing as much as it is the aspect ratio. If you look at any project page, you'll see that the image is this very wide, not so tall image that looks pretty on the page but needs some special cropping love to pick up the "important" parts of the picture. 

If we just try to cram a normal, say, 2:3 image into that space we're going to end up with lots of space on the sides, which will look weird. But putting the full height in that space will also push the content down pretty far, which will also look weird.

See Airbnb for what I think we should do (option 1 I outline above): https://www.airbnb.com/rooms/686128

**Comment by spacemunkay** [comment]
It looks like a responsive cropping interface is needed for either solution, as well as a Lightbox?  

@jcn I'm trying to clarify these "help wanted" issues such that someone who has never used our app can help.  I'm still unclear of what's desired for this issue.  Could you provide steps and screenshots of the problem, and possibly a mock of the fix?

**Comment by jcn** [comment]
The current proposal which @deadroxy is working on is to have 5 templates for images to drive people into a lightbox mode to see the entire image. The templates follow (with the single-image template being the same as it is on the live site).

![p2iio5cgne7s0nqaplb2fj95a1k0ogn0r](https://user-images.githubusercontent.com/2909/57333803-e00bb580-70eb-11e9-9dfc-0b131a5deda8.png)

![Screen Shot 2019-04-29 at 1 34 48 AM](https://user-images.githubusercontent.com/2909/57333808-e4d06980-70eb-11e9-8d3f-efce18076b2c.png)

![Screen Shot 2019-04-29 at 1 57 57 AM](https://user-images.githubusercontent.com/2909/57333811-e8fc8700-70eb-11e9-9fde-05a00beb30f4.png)

![Screen Shot 2019-04-29 at 1 41 31 AM](https://user-images.githubusercontent.com/2909/57333815-edc13b00-70eb-11e9-8f60-9a771cbf8d8a.png)
