### ISSUE TITLE
Loading of project pages stalls below image

### ISSUE THREAD

**Issue by avicaplan** [awesomefoundation/awesomebits#179]
Loading of project pages currently stalls after the horizontal rule under "[Chapter] project funded by [applicant]." After about a minute, the rest of the page loads. Same behaviour in both Firefox and Safari.

**Comment by jcn** [comment]
I am not seeing this behavior right now, though it might be related to the RSS feed for one of the projects you're looking at. If you're still seeing this problem, please let us know:

* the project page you're looking at (specific URL)
* the browser and OS you're using

**Comment by avicaplan** [comment]
Happens on all project pages, in Safari 8.0.3 and Firefox 36.0, both on MacOS X 10.10.2. Firefox status reports "Looking up s7.addthis.com" before rest of the page finally loads, and the social media buttons don't appear. No issue when loading these pages on my Blackberry -- but the social media buttons don't appear. So it looks like a problem with these may be what is causing the delayed loading.

**Comment by jcn** [comment]
addthis.com is the service we use to add social sharing to our project pages. It's possible that there are temporary connectivity problems from your machine / ISP to the addthis service. If this keeps up for a while we can think about disabling addthis, but like I said, I haven't actually seen this problem from my machine or my mobile device, and I checked and their status page isn't indicating a mass outage or anything like that.

**Comment by jcn** [comment]
Closing this and assuming it was a transient problem with addthis.com.
