### ISSUE TITLE
hyperlinks to open new

### ISSUE THREAD

**Issue by hnaylor** [awesomefoundation/awesomebits#183]
Please make the links in proposals open new tabs or windows
in the browser, instead of replacing the page I am looking at.
(as I recall this would be "target=blank" in html)
thanks
Hilary
SF Chapter

**Comment by jcn** [comment]
Hi Hilary, as a workaround for now, if you hold down the Command (⌘) key (on a Mac) or the Control key (on Windows) when you click a link, it will open in a new window.

**Comment by jcn** [comment]
I made this change, finally!
