### ISSUE TITLE
Add next and previous links to a project page

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#198]
Add next and previous links to project pages to make it easier for visitors to cycle through projects.

**Comment by spacemunkay** [comment]
*Issue*
Using a desktop computer.  Visit https://www.awesomefoundation.org/en/chapters/sf to see a chapter's page of projects.  Click on one image to go to 'show' an individual project's detail page (example: https://www.awesomefoundation.org/en/projects/101079-aaron-swartz-day-vr-museum-art-gallery-fun-house).  Note that the only way to see the next project listed on the chapter page (https://www.awesomefoundation.org/en/chapters/sf) is to use the browser back button and click on the next image.  

*Feature*
Add a 'Next project' and 'Previous project' link at the bottom or top of the detail page image.  This means that individual project pages will need to know their position in the chapter summary page.

*Mockup*
https://www.awesomefoundation.org/en/projects/101079-aaron-swartz-day-vr-museum-art-gallery-fun-house
<img width="1026" alt="screen shot 2018-05-29 at 11 01 26 pm" src="https://user-images.githubusercontent.com/384389/40701808-43fb8c66-6394-11e8-9834-2c908dcd147c.png">
