### ISSUE TITLE
Remove the classic uploader

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#209]
I would like to use an environment or config variable the way we determined if the s3 uploader was available so we could turn that back on again in case something goes wrong with s3 at some point in the future. See: https://github.com/awesomefoundation/awesomebits/blob/master/app/views/projects/_form.html.erb#L44-L47 and https://github.com/awesomefoundation/awesomebits/blob/master/app/helpers/projects_helper.rb#L30-L46

@avicaplan from a tech support perspective, have we had many/any complaints from people not being able to upload images since we switched over to the S3 uploader?

**Comment by avicaplan** [comment]
No complaints that I'm aware of!
