### ISSUE TITLE
Donate page

### ISSUE THREAD

**Issue by Chrysaora** [awesomefoundation/awesomebits#219]
Set up a page, linked to from the front page, that allows visitors to donate to IHAS. This would require a paragraph or two of copy about what the money could go towards, and a donate button hooked up to either our Paypal or Stripe accounts (or both?)

**Comment by jcn** [comment]
Not going to implement this until we know what the text should be and what the ultimate goal of this page is. There was presumably a conversation about encouraging donations to IHAS, but without knowing what the funds would be going toward, it'll make it harder to figure out what this page actually is.

**Comment by tungly** [comment]
Is it always the case that the fund recipient is required before funds are committed? Trustees act as a proxy for the recipient in a sense... How could we implement such a proxy contained in one web page?

**Comment by jcn** [comment]
This donation form is live at the new www.awesomestudies.org site.
