### ISSUE TITLE
Cleaner URLs for chapter pages

### ISSUE THREAD

**Issue by avicaplan** [awesomefoundation/awesomebits#235]
Current chapter URLs are a bit too clumsy for chapters to use directly for publicity (awesomefoundation.org/localization/chapters/chaptername), and registering and forwarding a domain is a technical barrier to some. It would be great if we had chaptername.awesomefoundation.org or awesomefoundation.org/chaptername redirects. We would need to add a dropdown in the chapter information screen for the default localization to be specified.

**Comment by jcn** [comment]
@avicaplan This was a great idea. It's done now, and as a bonus I even added the `/apply` shortcut (i.e. http://ottawa.awesomefoundation.org/apply)

**Comment by avicaplan** [comment]
Great -- thanks, @jcn!

I wonder if it might be clearer to deans to say something like "Language for xxx.awesomefoundation.org" instead of "Redirect locale."

**Comment by jcn** [comment]
Sounds good - I’m going to source the translations and then I’ll change it.
