### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by zarino** [awesomefoundation/awesomebits#244]
Just spotted two bits of Spam in this month’s applicants for the Liverpool chapter. Not sure where I should report them. I've “Hidden” them for now. Application IDs are 69939 and 69880.

![screen shot 2016-09-21 at 09 54 58](https://cloud.githubusercontent.com/assets/739624/18704416/b7214886-7fe1-11e6-84a8-04caa66b89ba.png)

**Comment by zarino** [comment]
Oh, and another. ID 70115.

**Comment by jcn** [comment]
I'm not fully convinced that 70115 is spam, as opposed to just a weirdly written, and incorrectly submitted, submission. 

The other two are clearly spam, but unless we're seeing a ton of them (i.e. unless it's automated) I'm not sure what we can do about this. If this becomes a really serious problem, re-report it or re-open this issue and we can look into some automated spam detection options, but as of now, I'm not sure that it warrants any more than what we're doing now.

**Comment by zarino** [comment]
> If this becomes a really serious problem, re-report it or re-open this issue

Will do! Worth saying, it’s the first time I’ve ever seen spam submissions, in 3 years of awesomeing.

**Comment by jcn** [comment]
Yeah, I suspect that sometimes spammers come through, try it out, realize that it's not actually going to help them at all (i.e. the links don't end up being public) and then they give up.
