### ISSUE TITLE
Fix the weirdness that is "Congo, Democratic Republic of the"

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#278]
We are using the `country_select` gem that has the DRC listed as in the title. This ends up looking a bit weird, especially since we're using the country name as indicated in the chapter dropdown and on the chapter page.

There might be a way of addressing this in the gem, or somewhere else.

**Comment by avicaplan** [comment]
As we no longer have an active chapter in DRC, this can probably be closed.
