### ISSUE TITLE
Only one row of chapters per country visible in IE 11

### ISSUE THREAD

**Issue by avicaplan** [awesomefoundation/awesomebits#406]
![ie](https://user-images.githubusercontent.com/4410290/63608774-cc556380-c5a3-11e9-97a8-30802d7a5ebd.jpg)

**Comment by jcn** [comment]
I just fixed that other thing you hated so much with the nav (#407) - that didn't happen to fix this as well did it? (I don't have access to IE 11 right now to test)

**Comment by avicaplan** [comment]
In fact it does!
