### ISSUE TITLE
Do not allow non-web images to be uploaded to a project

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#61]
Currently, the Photo model does not limit the kind of attachment it can have, which means that people have been uploading TIF and PDF files, which, when displayed on the homepage or on the project page, just break (since we're expecting them to be images).

Add a restraint to the paperclip attachment to prevent this and add the appropriate error notifications.

**Comment by aripollak** [comment]
Could this be revisited? I regularly see applications with attached images that not all browsers support, like HEIC. Could the `image/*` restriction just be limited to the set of images that all modern browsers support?
