### ISSUE TITLE
"Winner" button shown to non-deans on a particular project

### ISSUE THREAD

**Issue by mitcho** [awesomefoundation/awesomebits#89]
Today during deliberations, many of us non-deans in Boston pulled up this page and noticed that the "winner" button was visible on this project:

http://www.awesomefoundation.org/en/chapters/boston/projects/18862

The button is not visible (as expected) for all other projects we have seen this evening.

**Comment by karabee** [comment]
I can't find where in the repository this feature change is located to comment on, so I'm going to paste it here with an implementation request:

> We're actually planning on changing the functionality so that any user can actually assign the winner - since so many chapters have rotating dean / website responsibilities, limiting the functionality just to the dean is probably unnecessary

*If it is implemented that EVERY user has access to the "Winner" button, can something be done to protect from accidental clicking of the "Winner" button. I know if everyone had it, there would be a lot of accidental "Winner" postings when people are clicking "Awesome" to nominate something for the shortlist.

Two ideas on how to avoid this:
1. Move the location of the button away from the Awesome button 
2. Make it clear with a confirmation message that clicking that button means that the project is going to go "live" on the chapter page as a fellowship recipient
3. Bury this option as viewable only when a non-Dean user has clicked into the application. It would still be great to have the safeguard of ideas 1 and 2.

**Comment by jcn** [comment]
>  you could actually set a project to be the winner for another chapter

This bug has been fixed in #328. The rest of this is a non-bug, and the editing/marking as a winner was changed in #326 so I'm going to close this.
